# Generated by Django 4.1.5 on 2023-02-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('factor', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_tag', models.CharField(blank=True, default='ausstehend', max_length=100)),
                ('image', models.ImageField(blank=True, unique=True, upload_to='artist_images')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('production_date', models.IntegerField(blank=True, default=None)),
                ('materials', models.CharField(blank=True, max_length=300)),
                ('width', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('depth', models.IntegerField(blank=True, default=0)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('artist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='databank.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('buyer', models.CharField(blank=True, max_length=100, null=True)),
                ('tax', models.IntegerField(blank=True, choices=[(19, '19'), (7, '7')], default=19)),
                ('decree', models.IntegerField(blank=True, choices=[(0, '0'), (5, '5'), (10, '10'), (15, '15'), (20, '20')], default=0)),
                ('status', models.CharField(blank=True, choices=[('Gelagert', 'Gelagert'), ('Verkauft', 'Verkauft')], default='Gelagert', max_length=20)),
                ('work', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='databank.work')),
            ],
        ),
    ]
