# Generated by Django 4.1.5 on 2023-02-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, choices=[('Wuppertal', 'Wuppertal'), ('Nah&Gut', 'Nah&Gut'), ('Düsseldorf', 'Düsseldorf'), ('Verkauft', 'Verkauft'), ('Geliefert', 'Geliefert')], default='Wuppertal', max_length=20),
        ),
    ]
