# Generated by Django 4.1.5 on 2023-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0002_alter_status_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='storage_tag',
        ),
        migrations.AddField(
            model_name='artist',
            name='storagetag',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
        migrations.AddField(
            model_name='work',
            name='buyer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='decree',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (5, '5'), (10, '10'), (15, '15'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='salesdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='salesstatus',
            field=models.CharField(blank=True, choices=[('Wuppertal', 'Wuppertal'), ('Nah&Gut', 'Nah&Gut'), ('Düsseldorf', 'Düsseldorf')], default='Verfügbar', max_length=20),
        ),
        migrations.AddField(
            model_name='work',
            name='storagestatus',
            field=models.CharField(blank=True, choices=[('Wuppertal', 'Wuppertal'), ('Nah&Gut', 'Nah&Gut'), ('Düsseldorf', 'Düsseldorf')], default='Wuppertal', max_length=20),
        ),
        migrations.AddField(
            model_name='work',
            name='tax',
            field=models.IntegerField(blank=True, choices=[(19, '19'), (7, '7')], default=19),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
