# Generated by Django 4.1.5 on 2023-02-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0003_remove_work_storage_tag_artist_storagetag_work_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
