# Generated by Django 4.1.5 on 2023-02-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0004_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='salesstatus',
            field=models.CharField(blank=True, choices=[('Verfügbar', 'Verfügbar'), ('Verkauft', 'Verkauft'), ('Geliefert', 'Geliefert')], default='Verfügbar', max_length=20),
        ),
    ]
