# Generated by Django 4.1.5 on 2023-02-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0005_alter_work_salesstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, default='default.png', unique=True, upload_to='artist_images'),
        ),
        migrations.AlterField(
            model_name='work',
            name='salesdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
