# Generated by Django 4.1.5 on 2023-02-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0006_alter_work_image_alter_work_salesdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='salesstatus',
            field=models.CharField(blank=True, choices=[('Lager', 'Lager'), ('Verkauft', 'Verkauft'), ('Geliefert', 'Geliefert')], default='Lager', max_length=20),
        ),
    ]
