# Generated by Django 4.1.5 on 2023-02-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0007_alter_work_salesstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='factor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
