# Generated by Django 4.1.5 on 2023-03-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0008_alter_artist_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField()),
            ],
        ),
    ]
