# Generated by Django 4.1.5 on 2023-03-02 19:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0009_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='text_field',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
