# Generated by Django 4.1.5 on 2023-03-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0010_alter_test_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='salesstatus',
            field=models.CharField(blank=True, choices=[('Verkauft', 'Verkauft'), ('Geliefert', 'Geliefert')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='work',
            name='storagestatus',
            field=models.CharField(blank=True, choices=[('Wuppertal', 'Wuppertal'), ('Nah&Gut', 'Nah&Gut'), ('Düsseldorf', 'Düsseldorf'), ('Abgegeben', 'Abgegeben')], default='Wuppertal', max_length=20),
        ),
    ]
