# Generated by Django 4.1.5 on 2023-03-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0012_renter_delete_test_work_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='decree',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (5, '5'), (10, '10'), (15, '15'), (20, '20')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='storagestatus',
            field=models.CharField(blank=True, choices=[('Wuppertal', 'Wuppertal'), ('Nah&Gut', 'Nah&Gut'), ('Düsseldorf', 'Düsseldorf'), ('Vermietet', 'Vermietet'), ('Abgegeben', 'Abgegeben')], default='Wuppertal', max_length=20),
        ),
        migrations.AlterField(
            model_name='work',
            name='tax',
            field=models.IntegerField(blank=True, choices=[(19, '19'), (7, '7')], default=19, null=True),
        ),
    ]
